up_db() {
  echo
  echo "==> Updating desktop database..."
  update-desktop-database -q
  update-mime-database /usr/share/mime &> /dev/null
}

nag() {
cat << EOM

==> If you are even a little serious about Ardour,
==> please fund features, donate and/or subscribe
==> as a financial supporter:

http://ardour.org/bugbounty
http://ardour.org/subscribe2
http://ardour.org/donate2

==> We currently check out a tagged revision from
==> the development tree to offer you this package,
==> so we encourage you to download an official
==> release tarball:

http://ardour.org/download

EOM
}

post_install() {
  ln -s /usr/bin/ardour2 /usr/bin/ardour
  ln -s /usr/share/ardour2/icons/ardour_icon_48px.png \
    /usr/share/pixmaps/ardour.png

  up_db
  nag
}

post_upgrade() {
  up_db
  nag
}

post_remove() {
  rm -f /usr/bin/ardour
  rm -f /usr/share/pixmaps/ardour.png
  up_db
}

# vim:set ts=2 sw=2 et:
