--- Makefile.orig	2007-06-19 10:19:01.000000000 +0200
+++ Makefile	2009-01-03 18:21:33.000000000 +0100
@@ -1,7 +1,7 @@
-PREFIX = /usr/local
+PREFIX = /usr
 
 CC = g++
-OPTS = -O2 -ffast-math -funroll-loops -Wall -fPIC -DPIC
+OPTS = -O2 -funroll-loops -Wall -fPIC -DPIC
 #OPTS = -g -DDEBUG 
 
 -include defines.make
@@ -48,7 +48,7 @@
 	$(CC) $(CFLAGS) -S $<
 
 .cc.o: depend
-	$(CC) $(CFLAGS) -I/usr/local/include -c $<
+	$(CC) $(CFLAGS) -I/usr/include -c $<
 
 tags: $(SOURCES) $(HEADERS)
 	@echo making tags
