import glob
import os
import re
prefix = "/usr/lib/pd"

env = Environment(CPPPATH = Split(prefix + '/src /usr/include /usr/local/include .'), CPPDEFINES=['PD','UNIX'], SHLIBPREFIX = '', SHLIBSUFFIX = '.pd_linux', CCFLAGS = '-pipe -O2 -g')

if ARGUMENTS.get('debug', 0):
  env["CPPDEFINES"] += ["DEBUG"]

external = env.SharedLibrary('ladspa~',glob.glob('*.c'))
env.Alias('install', env.Install(os.path.join(prefix, 'extra'), external))
env.Alias('install', env.Install(os.path.join(prefix, 'doc/5.reference'),'ladspa~-help.pd'))
Default(external)
