--- Makefile	2011-01-11 00:28:31.593333566 -0200
+++ Makefile.orig	2010-08-13 09:16:33.000000000 -0300
@@ -18,7 +18,7 @@

 #  No trailing slash!
 #INSTALLPATH=/hom/kjetism/site
-INSTALLPATH=/usr/local
+INSTALLPATH=/usr



 # If you don't want to compile sndlib with jack-support, set SNDLIBWITHJACK to nothing.
@@ -99,10 +99,10 @@
 #
 # No!!! Don't set this flag. (very buggy!) Use sndlib's jack-support instead.
 #
-USEJACK=
+#USEJACK=

 #-DUSEJACK

-#USEJACK=-DUSEJACK
+USEJACK=-DUSEJACK


@@ -131,8 +131,8 @@
 #ADDITIONALCFLAGS will be added to the CFLAGS line.
 #ADDITIONALLDFLAGS will be added to the LDFLAGS line.

-ADDITIONALCFLAGS= -O3 -g -fPIC --fast-math -Ipackages/sndlib -I/usr/local/include
-ADDITIONALLDFLAGS=  packages/sndlib/sndlib.a -L/usr/local/lib -lsndfile `cat jacklib.comp` -lm -lpthread -ldl -L.
+ADDITIONALCFLAGS= -O3 -g -fPIC --fast-math -Ipackages/sndlib -I/usr/include
+ADDITIONALLDFLAGS=  packages/sndlib/sndlib.a -L/usr/lib -lsndfile `cat jacklib.comp` -lm -lpthread -ldl -L.



@@ -150,7 +150,7 @@
 # You most probably want to install your own python if you are using
 # RedHat 8 (see INSTALL file).

-PYTHONEXE=/usr/bin/env python
+PYTHONEXE=/usr/bin/python2
 #PYTHONEXE=/site/bin/python2.2
 #PYTHONEXE=/usr/python-pygtk1/bin/python
 #PYTHONEXE=/usr/local/bin/python2.2
@@ -178,10 +178,10 @@
 #DAS-LDFLAGS= /hom/kjetism/lib/sndlib.a /site/lib/libsndfile.a /site/lib/libXm.a -L/usr/X11R6/lib -lXt -lXext -lX11 -lXp -lXpm -lSM -lXIE -lICE -lm -lpthread -lasound -ldl -static
 #/usr/lib/libXm.so.2
 #Dynamic compilation:
-MOTIF-LIBS=packages/openmotif-2.3.2/lib/Xm/.libs/libXm.a -lXmu -lXt -lXext -lXp -lXft -lXrender -lfontconfig `freetype-config --libs` -lX11 -ljpeg -lpng
+MOTIF-LIBS=packages/openmotif-2.3.2/lib/Xm/.libs/libXm.a -lXmu -lXt -lXext -lXp -lXft -lXrender -lfontconfig `freetype-config --libs` -lX11 -ljpeg -lpng
 DAS-LDFLAGS= $(MOTIF-LIBS) -L$(X11PATH)/lib -lXt -lX11 $(ADDITIONALLDFLAGS) -ljack -lsamplerate
 #DAS-LDFLAGS= -L$(MOTIFPATH)/lib -Lpackages/openmotif-2.3.2/lib/Xm/.libs/libXm.a -lXm -L$(X11PATH)/lib -lXt -lX11 $(ADDITIONALLDFLAGS) -ljack -lsamplerate

@@ -301,14 +301,14 @@


 run:
-	python ../bin/ceres.py
+   python2 ../bin/ceres.py


 ../bin/ceres: Makefile
 #	rm -f ../bin/ceres
 	echo "#!/bin/sh" >../bin/ceres
 	echo 'export LD_PRELOAD="$(PYGTK1PATH)/lib/libgtk-1.2.so.0 $(PYGTK1PATH)/lib/libgdk-1.2.so.0 $(PYGTK1PATH)/lib/libgmodule-1.2.so.0 $(PYGTK1PATH)/lib/libglib-1.2.so.0 $(PYGTK1PATH)/lib/libgthread.so"' >>../bin/ceres
-	echo "LD_LIBRARY_PATH=$(PYGTK1PATH)/lib:$LD_LIBRARY_PATH python $(SHAREPATH)/bin/ceres.py \$$@" >>../bin/ceres
+   echo "LD_LIBRARY_PATH=$(PYGTK1PATH)/lib:$LD_LIBRARY_PATH python2 $(SHAREPATH)/bin/ceres.py \$$@" >>../bin/ceres
 	chmod a+rx ../bin/ceres

 ../bin/ceres.py: ceres.py Makefile
